apiVersion: v1
kind: Secret
metadata:
  name: aline-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_DATABASE: YWxpbmVkYg== 
  MYSQL_USER: c3RlcGhlbmZyZWVk 
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  SECRET_KEY: ZVNoVm1ZcTN0Nnc5eiRDJkYpSkBOY1JmVWpXblpyNHU=

